# Generated by Django 6.0.4 on 2026-05-03 00:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Salon de Eventos', max_length=150)),
                ('whatsapp', models.CharField(default='0991234567', max_length=20)),
                ('correo', models.EmailField(default='contacto@correo.com', max_length=254)),
                ('direccion', models.CharField(blank=True, default='Esmeraldas, Ecuador', max_length=255)),
                ('tarifa_base_alquiler', models.DecimalField(decimal_places=2, default=350, max_digits=10)),
                ('invitados_incluidos', models.PositiveIntegerField(default=100)),
                ('costo_invitado_adicional', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=10)),
            ],
            options={
                'verbose_name': 'configuracion del negocio',
                'verbose_name_plural': 'configuraciones del negocio',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField()),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('abonado', 'Abonado'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='GastoFijoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('concepto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'gasto fijo mensual',
                'verbose_name_plural': 'gastos fijos mensuales',
                'ordering': ['-anio', '-mes', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_servicio', models.CharField(default='Servicio completo', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['precio_por_persona', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de evento',
                'verbose_name_plural': 'tipos de evento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CostoDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='negocio.contrato')),
            ],
            options={
                'verbose_name': 'costo directo',
                'verbose_name_plural': 'costos directos',
                'ordering': ['concepto'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tentativa', models.DateField()),
                ('numero_invitados', models.PositiveIntegerField()),
                ('tipo_servicio', models.CharField(choices=[('servicio_completo', 'Servicio completo'), ('alquiler', 'Alquiler del local'), ('no_seguro', 'Aun no estoy seguro')], max_length=30)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('confirmado', 'Confirmado'), ('convertido', 'Convertido'), ('descartado', 'Descartado')], default='nuevo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('ultimo_contacto', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='negocio.cliente')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='negocio.paquete')),
                ('tipo_evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='negocio.tipoevento')),
            ],
            options={
                'verbose_name': 'cotizacion',
                'verbose_name_plural': 'cotizaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='cotizacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='negocio.cotizacion'),
        ),
    ]
